Avro error handling
NYPL-discovery/discovery-poster pull request #17
Opened 2017-07-25 18:45 UTC by jobinthomasnypl

2017-07-25 18:49 UTC, EdwinGuzman commented on package.json
> +    "avsc": "https://github.com/NYPL-discovery/avsc.git#master",
You're not going to depend on NPM or on the local copy with local changes.

2017-07-25 19:00 UTC, EdwinGuzman requested changes
Just run it through your usual linter and it should be good to go.

2017-07-25 19:01 UTC, jobinthomasnypl commented on package.json
> +    "avsc": "https://github.com/NYPL-discovery/avsc.git#master",
Yeah we forked the avsc repo to NYPL-discovery and made changes there.

2017-07-25 19:02 UTC, jobinthomasnypl commented on package.json
> +    "avsc": "https://github.com/NYPL-discovery/avsc.git#master",
Cool, I will run using standard.js

2017-07-25 19:24 UTC, EdwinGuzman commented
Thanks for running it through Standard 👍

2017-07-25 19:24 UTC, EdwinGuzman approved these changes

2017-08-15 19:08 UTC, jobinthomasnypl commented
@EdwinGuzman @nonword this is great news that we don't need a forked repo and the issue was we were not calling the callback() explicitly and passing the error. If you guys can take a look at the PR and let me know that will be great.

2017-08-17 15:10 UTC, merged